name: Release on Push to release Branch

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Get latest tag and increment
        id: get_version
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | grep '^v[0-9]\+$' | head -n 1)
          if [ -z "$latest_tag" ]; then
            new_tag="v1"
          else
            version_number=${latest_tag#v}
            new_number=$((version_number + 1))
            new_tag="v$new_number"
          fi
          echo "tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: ${{ steps.get_version.outputs.tag }}
          files: |
            dist/*.js
            dist/*.d.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
